#!/bin/sh
#
# Set up environment variables for general build tool to operate
#
if ! [ -f ./buildenv ]; then
	echo "Need to source from the buildenv directory" >&2
	return 0
fi

export ZOPEN_ROOT="${PWD}"
export ZOPEN_TYPE="GIT"
export ZOPEN_TARBALL_URL="https://ftp.gnu.org/gnu/help2man/help2man-1.49.2.tar.xz"
export ZOPEN_TARBALL_DEPS="curl xz make m4 perl autoconf"

export ZOPEN_GIT_URL="https://github.com/Distrotech/help2man.git"
export ZOPEN_GIT_DEPS="git make m4 perl autoconf automake xz"

export ZOPEN_EXTRA_CFLAGS=""
export ZOPEN_EXTRA_LDFLAGS=""
